pos_dict = {"ADJ": "adjective",
"ADP": "adposition",
"ADV": "adverb",
"AUX": "auxiliary verb",
"CONJ": "coordinating conjunction",
"DET": "determiner",
"INTJ": "interjection",
"NOUN": "noun",
"NUM": "numeral",
"PART": "particle",
"PRON": "pronoun",
"PROPN": "proper noun",
"PUNCT": "punctuation",
"SCONJ": "subordinating conjunction",
"SYM": "symbol",
"VERB": "verb",
"X": "other"}

agg_data = {'Sum' : 0,
'Min' : 1,
'Max' : 2,
'Count' : 3,
'Distinct Count' : 4,
'Average' : 5,
'Value' : 6,
'Top' : 7,
'Bottom' : 8}

operator_data = {'EqualTo' : 0,
'LessThan' : 1,
'LessThanOrEqualTo' : 2,
'GreaterThan' : 3,
'GreaterThanOrEqualTo' : 4,
'NotEqualTo' : 5,
'StartsWith' : 6,
'NotStartsWith' : 7,
'EndsWith' : 8,
'NotEndsWith' : 9,
'Contains' : 10,
'NotContains' : 11,
'Between' : 12,
'NotBetween' : 13,
'OneOf' : 14,
'NotOneOf' : 15}

table_data = {'Products':['ProductID',
'ProductName',
'SupplierID',
'CategoryID',
'QuantityPerUnit',
'UnitPrice',
'UnitsInStock',
'UnitsOnOrder',
'ReorderLevel',
'Discontinued']
,'Categories':['CategoryID',
'CategoryName',
'Description',
'Picture']
,'OrderDetails':['OrderDetailsID',
'OrderID',
'ProductID',
'UnitPrice',
'Quantity',
'Discount']
,'Orders':['OrderID',
'CustomerID',
'EmployeeID',
'OrderDate',
'RequiredDate',
'ShippedDate',
'Shipvia',
'Freight',
'ShipName',
'ShipAddress',
'ShipCity',
'ShipRegion',
'ShipPostalCode',
'ShipCountry']
,'Employees':['EmployeeID',
'LastName',
'FirstName',
'Title',
'BirthDate',
'HireDate',
'Address',
'City',
'Region',
'PostalCode',
'Country',
'HomePhone',
'Extension',
'Photo',
'Notes',
'ReportsTo',
'PhotoPath']
}
mapped_data={'Employees':'Employees_0'}
